/*const char *onenet_base_dp_upload_str="{"
"\"id\":%d,"
"\"dp\":{"
"\"lamp\":[{"
"\"v\":%d"
"}],"
"\"temperatrue\":[{"
"\"v\":%d"
"}],"
"\"humidity\":[{"
"\"v\":%d"
"}],"
"\"power\":[{"
"\"v\":%d"
"}],"
"\"sound\":[{"
"\"v\":%d"
"}],"
"\"light_d\":[{"
"\"v\":%d"
"}],"
"\"light_b\":[{"
"\"v\":%d"
"}],"
"\"light\":[{"
"\"v\":%d"
"}],"
"\"mq2_d\":[{"
"\"v\":%d"
"}],"
"\"mq2\":[{"
"\"v\":%d"
"}],"
"\"box1\":[{"
"\"v\":%d"
"}],"
"\"box2\":[{"
"\"v\":%d"
"}],"
"\"touch\":[{"
"\"v\":%d"
"}],"
"\"human\":[{"
"\"v\":%d"
"}],"
"\"door\":[{"
"\"v\":%d"
"}],"
"\"motor\":[{"
"\"v\":%d"
"}],"
"\"alarm\":[{"
"\"v\":%d"
"}],"
"\"relay1\":[{"
"\"v\":%d"
"}],"
"\"relay2\":[{"
"\"v\":%d"
"}]"
"}"
"}";*/
const char *onenet_base_dp_upload_str1="{"
"\"id\":%d,"
"\"dp\":{"
"\"lamp\":[{"
"\"v\":%d"
"}],"
"\"temperatrue\":[{"
"\"v\":%d"
"}],"
"\"humidity\":[{"
"\"v\":%d"
"}],"
"\"power\":[{"
"\"v\":%d"
"}]"
"}"
"}";



const char *onenet_base_dp_upload_str2="{"
"\"id\":%d,"
"\"dp\":{"
"\"sound\":[{"
"\"v\":%d"
"}],"
"\"light_d\":[{"
"\"v\":%d"
"}],"
"\"light_b\":[{"
"\"v\":%d"
"}],"
"\"light\":[{"
"\"v\":%d"
"}]"
"}"
"}";


const char *onenet_base_dp_upload_str3="{"
"\"id\":%d,"
"\"dp\":{"
"\"mq2_d\":[{"
"\"v\":%d"
"}],"
"\"mq2\":[{"
"\"v\":%d"
"}],"
"\"box1\":[{"
"\"v\":%d"
"}],"
"\"box2\":[{"
"\"v\":%d"
"}]"
"}"
"}";
const char *onenet_base_dp_upload_str4="{"
"\"id\":%d,"
"\"dp\":{"
"\"touch\":[{"
"\"v\":%d"
"}],"
"\"human\":[{"
"\"v\":%d"
"}],"
"\"door\":[{"
"\"v\":%d"
"}],"
"\"motor\":[{"
"\"v\":%d"
"}]"
"}"
"}";


const char *onenet_base_dp_upload_str5="{"
"\"id\":%d,"
"\"dp\":{"
"\"alarm\":[{"
"\"v\":%d"
"}],"
"\"relay1\":[{"
"\"v\":%d"
"}],"
"\"relay2\":[{"
"\"v\":%d"
"}]"
"}"
"}";


const char *onenet_base_dp_upload_str6="{"
"\"id\":%d,"
"\"dp\":{"
"\"sound_num\":[{"
"\"v\":%d"
"}],"
"\"light_bum\":[{"
"\"v\":%d"
"}],"
"\"mq2_num\":[{"
"\"v\":%d"
"}]"
"}"
"}";


const char *onenet_base_dp_upload_str_nfc="{"
"\"id\":%d,"
"\"dp\":{"
"\"ID\":[{"
"\"v\":\"%s\""
"}],"
"\"ID_last\":[{"
"\"v\":\"%s\""
"}]"
"}"
"}";

const char *onenet_base_dp_upload_str_lend="{"
"\"id\":%d,"
"\"dp\":{"
"\"LEND\":[{"
"\"v\":{"
"\"user\":\"%s\","
"\"device\":\"%s\""
"}"
"}]"
"}"
"}";

//int id;
#define FILL_MSG1	os_snprintf(pub_buf1, sizeof(pub_buf1), onenet_base_dp_upload_str1, id, device_state.lamp,device_state.temperature,device_state.humidity,device_state.power)

#define FILL_MSG2	os_snprintf(pub_buf2, sizeof(pub_buf2), onenet_base_dp_upload_str2, id, device_state.sound,device_state.light_d,device_state.light_b,device_state.light)

#define FILL_MSG3	os_snprintf(pub_buf3, sizeof(pub_buf3), onenet_base_dp_upload_str3, id,device_state.mq2_d,device_state.mq2,device_state.box1,device_state.box2)

#define FILL_MSG4	os_snprintf(pub_buf4, sizeof(pub_buf4), onenet_base_dp_upload_str4, id,device_state.touch,device_state.human,device_state.door,device_state.motor)

#define FILL_MSG5	os_snprintf(pub_buf5, sizeof(pub_buf5), onenet_base_dp_upload_str5, id,device_state.alarm,device_state.relay1,device_state.relay2)
	
#define FILL_MSG6	os_snprintf(pub_buf6, sizeof(pub_buf6), onenet_base_dp_upload_str6, id,device_state.sound_num,device_state.light_num,device_state.mq2_num)

#define FILL_MSG_NFC	 os_snprintf(pub_buf_nfc, sizeof(pub_buf_nfc), onenet_base_dp_upload_str_nfc, 99999,device_state.nfc_id_now,device_state.nfc_id_last)

#define FILL_MSG_LEND os_snprintf(pub_buf_lend, sizeof(pub_buf_lend), onenet_base_dp_upload_str_lend, 88888,device_state.nfc_id_last,device_state.nfc_id_now)
